### ISSUE TITLE
Area Livery Mod not working

### ISSUE THREAD

**Issue by Nelson340** [ClonkAndre/ScriptHookDotNet-for-IVSDKDotNet#13]
Using the Stanier and Merit police cars from:
https://gtaforums.com/topic/974798-donnits-bakery/#comments
And the script required to give them area-specific liveries:
https://www.lcpdfr.com/downloads/gta4mods/scripts/5629-area-livery-mod/
I noticed there were still LCPD cars spawning in Alderney, Alderney State Trooper cars in Liberty City, and Port Patrol and Highway Patrol cars spawning everywhere. Attached is a picture of what the console shows
![Screenshot_20240628_175924](https://github.com/ClonkAndre/ScriptHookDotNet-for-IVSDKDotNet/assets/22733426/7e3ea5bd-91d8-4d40-9e0a-a6cf5ee5f0db)
[IVSDKDotNet.log](https://github.com/user-attachments/files/16037449/IVSDKDotNet.log)
Game version is 1.0.8.0

**Comment by ClonkAndre** [comment]
Thanks for the report! A fix for that will be shipped in the upcoming version of IV-SDK .NET!

**Comment by ClonkAndre** [comment]
The error is fixed now.
