### ISSUE TITLE
Car Security Script Issue: Stops working after game Load screens

### ISSUE THREAD

**Issue by Ex3cutionerX** [ClonkAndre/ScriptHookDotNet-for-IVSDKDotNet#23]
I'm experiencing an issue with the "Car Security" script ([GTA Forums link](https://gtaforums.com/topic/763074-relivnet-carsecurity-script-by-nyolc8/), [GitHub link](https://github.com/ClonkAndre/ScriptHookDotNet-for-IVSDKDotNet/issues/url)). The script works perfectly after the first loading screen and i can track my car on map with Z key and lock/unlock car door with the N key, but if I die or any mission/related game load occurs, the script stops functioning. It only resumes working if I reload it manually through the IVsdk Manager. Could you help me? Thanks in advance!

**Comment by ClonkAndre** [comment]
So i just checked out what could be the problem with this mod, and i came to the conclusion that it might actually be the script that's broken. So i'm closing this for now but if you can proof me wrong (like with the script working fine on old ScriptHookDotNet) then feel free to reopen this issue.
