### ISSUE TITLE
Project Thunder don't work Anymore

### ISSUE THREAD

**Issue by Ex3cutionerX** [ClonkAndre/ScriptHookDotNet-for-IVSDKDotNet#28]
Project Thunder script [https://github.com/ClonkAndre/ProjectThunderIV](url) don't work with new IVSDK 1.7 update. Here's the error it's giving on the console menu: [04/10/2024 05:00:14] An error occurred while processing 'Tick' event for script 'ProjectThunderIV.Main'. Aborting script. Details: System.MissingMethodException: Method not found: 'CCL.GTAIV.AnimationController.PedAnimationController CCL.GTAIV.IVPedExtensions.GetAnimationController(IVSDKDotNet.IVPed)'.
 in ProjectThunderIV.Main.<>c__DisplayClass47_0.<PlayThunderSound>b__0() in ProjectThunderIV.Main.ProcessDelayedCalls(Boolean calledFromUninitializeEvent) in ProjectThunderIV.Main.Main_Tick(Object sender, EventArgs e) in IVSDKDotNet.Script.RaiseTick() in Manager.Classes .FoundScript.RaiseTick() in Manager.Main.<>c__DisplayClass35_0.<RaiseTick>b__0(FoundScript fs) [04/10/2024 05:00:14] Aborting script ProjectThunderIV.Main... [04/10/2024 05 :00:14] Manager successfully aborted script ProjectThunderIV.Main.

**Comment by Ex3cutionerX** [comment]
I'm on 1.0.7.0 using ZolikaPatch and latest Liberty Tweaks 1.5 without Dxvk or Fusionfix

**Comment by ClonkAndre** [comment]
Project Thunder is not a ScriptHookDotNet mod. Please post this issue in the Project Thunder Issues page here on GitHub (https://github.com/ClonkAndre/ProjectThunderIV)
