### ISSUE TITLE
Scripthook.net  configuration files are not read correctly (or at all)

### ISSUE THREAD

**Issue by ChunkLeChuck** [ClonkAndre/ScriptHookDotNet-for-IVSDKDotNet#3]
I have been experimenting with different scripthook.net mods, namely Pickups V2.0  (https://www.gtagaming.com/pickups2-0-f23960.html) and Cautious Drivers (https://www.gtagaming.com/cautious-drivers-v1-3-f9052.html).
Now it seems like Pickups V2.0 does work by itself, any changes made in the configuration using the included .ini file of the mod are not being read at all.
Cautious Drivers is a fairly simple mod it will not even load (most likely because it cant read the config file)

Some mods like Arrest Warrant (https://www.gtagaming.com/arrest-warrant-updated-2-21-15-f10271.html) work, but again, nothing takes effect after changing .ini settings.

Easily reproducible issue , try any of these mods, try changing .ini settings like toggling weapon glow in pickups or alert indicator in Arrest warrant .ini files and see for yourself that no configuration files are being read.

Additionally the mods themselves only load when put into a 'scripts' folder inside the GTAIV main directory and don't work when placed inside the  '\IVSDKDotNet\scripts\'

**Comment by ClonkAndre** [comment]
This should now be fixed 👍
If there should still be any issues with scripts failing to read their configuration file properly, feel free to reopen this issue!
