### ISSUE TITLE
How do i report a mod which isn't working as expected?

### ISSUE THREAD

**Issue by ClonkAndre** [ClonkAndre/ScriptHookDotNet-for-IVSDKDotNet#9]
If you got as ScriptHookDotNet mod which is not quite working as expected, or it does not work the same as it did on the old ScriptHookDotNet, please post a new [issue](https://github.com/ClonkAndre/ScriptHookDotNet-for-IVSDKDotNet/issues).

**For the best chances of the problem being solved, here's what you should put in your issue:**
- \* Obviously the name of the mod (Preferable with a link to the download page).
- \* The version you tested this mod on (e.g. 1070, 1080 or whatever).
-  \* The version of IV-SDK .NET you currently have (Can be checked if you open up the in-game console by pressing "F4").
-  \* The version of the **ScriptHookDotNet.dll** file that is placed in the "**IVSDKDotNet -> bin**" folder.
- The content of the IV-SDK .NET log file.

 \* = Definitely required. Issues that not have this might get closed.

(Might expand the list in the future)

**Comment by Geresman** [comment]
NOT WORKING ⚠️​

Dialogue System Mod

- IV Version : 1.0.7.0

- IV-SDK.NET Version : 1.3

- ScriptHookDotNet.dll Version (located in the "IVSDKDotNet -> bin" folder) : 1.7.2.1

- IV-SDK.NET log File : 
[IVSDKDotNet.log](https://github.com/user-attachments/files/15523573/IVSDKDotNet.log)

- Mod Download Page : https://www.gtainside.com/en/gta4/mods/168783-grand-theft-auto-iv-dialogue-system-mod
